version: "3.8"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=secret 
      - POSTGRES_USER=root
      - POSTGRES_DB=simple_bank
    healthcheck:
      test: psql -h localhost -U root -d simple_bank -c "SELECT 1" || exit 1
      interval: 2s
      timeout: 10s
      retries: 15
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  
    
